# Site settings
title: M van Eijgen
name: Mitchel van Eijgen
tagline: Graphic designer who loves technology.
email: mvaneijgen@gmail.com
copyright: Mitchel van Eijgen
keywords:
phone: 06 38 63 27 35
address: Lange herenvest 122<br/>2011 BX Haarlem
kvk: 52348032
btw: NL044083002B01
twitter_username: mvaneijgen
github_username:  mvaneijgen
linkedin_username: mvaneijgen
codepen_username: mvaneijgen
avatar: "http://0.gravatar.com/avatar/8a68ce0259bbb16411035e487ecb27c5"

description: I am a graphic desigher from The Netherlands, working for my self since 2009 and recently under the name <a href="http://studioalloy.nl">Studio Alloy</a> as a collective of creative designer and developers.
about: <p>Al sinds jonge twintiger is Mitchel van Eijgen actief als ondernemer in de wereld van design, code en technische vernieuwing. Deze gadget freak is non-stop actief als technisch grafisch ontwerper met fascinatie voor innovaties en het automatiseren van zijn werk. En eigenlijk ook dagelijks bezig om de rest van zijn leven geautomatiseerd te maken.</p><p>Mitchel studeerde Grafisch ontwerp aan de Hogeschool van de kunsten in Utrecht, waar hij het inzicht kreeg dat voor hem de digitale wereld een onuitputtelijk bron van inspiratie is. Het kunnen praten over een mooie huisstijl of typografie in combinatie met de beste manier van het indelen van de achterliggende code is voor hem even belangrijk.</p><p>Sinds de start van zijn ondernemende leven had Mitchel altijd al de droom om een collectief te vormen met creatieve ondernemers op een gedeelde werkplek. Met het vormen van Studio Alloy is deze droom werkelijkheid geworden.</p>


# the base hostname & protocol for your site
url: "//mvaneijgen.nl/"
baseurl: "//mvaneijgen.nl/"
default_image: /mvaneijgen-grafisch-ontwerper.jpg

# Collections
collections:
  work:
    output: true
    permalink: /work/:title/
  product:
    output: false
  team:
    output: false
    permalink: /team/:title/

# Pre-processing

markdown: kramdown
safe: true
permalink: /blog/:title/ # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
sass:
    style: compressed
# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]

# Lists

tag_items: 20     # Applies to categories and tags lists
recent_items: 10  # Applies to recent posts, apps lists
related_items: 5  # Applies to related posts and apps lists

# Features

facebook: false       # Use facebook features
comments: none      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments
perspective: true
