# Site settings
title: M van Eijgen
name: Mitchel van Eijgen
tagline: Graphic designer who loves technology.
email: mvaneijgen@gmail.com
copyright: Mitchel van Eijgen
keywords:
phone: 06 38 63 27 35
twitter_username: mvaneijgen
github_username:  mvaneijgen
avatar: "http://0.gravatar.com/avatar/8a68ce0259bbb16411035e487ecb27c5"

description: I am a graphic desigher from The Netherlands, working for my self since 2009 and recently under the name <a href="http://studioalloy.nl">Studio Alloy</a> as a collective of creative designer and developers.

# the base hostname & protocol for your site
url: "http://mvaneijgen.nl/"
baseurl: "http://mvaneijgen.nl/"
default_image: /mvaneijgen-grafisch-ontwerper.jpg

# Collections
collections:
  cases:
    output: true
    permalink: /case/:title/
  product:
    output: true
  team:
    output: false
    permalink: /team/:title/

# Pre-processing

markdown: kramdown
highlighter: pygments
safe: true
permalink: /blog/:title/ # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
# sass:
#  style: :compressed

# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]

# Lists

tag_items: 20     # Applies to categories and tags lists
recent_items: 10  # Applies to recent posts, apps lists
related_items: 5  # Applies to related posts and apps lists

# Features

facebook: false       # Use facebook features
comments: none      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments
perspective: true
